### ISSUE TITLE
not working 'NoneType' object has no attribute 'cancel'

### ISSUE THREAD

**Issue by leonglo** [Its-Traadev/Fake-Verification-QR-Discord#2]
![image](https://user-images.githubusercontent.com/75845683/190263518-1c8683a4-e8a9-47ea-914c-332b6ea2007d.png)
getting this error since yesterday
any idea?

**Comment by SpecOpsCode** [comment]
Same issue for me using latest python version on linux machine, any solutions so far?

**Comment by Its-Traadev** [comment]
Fixed
