### ISSUE TITLE
'NoneType' object has no attribute 'cancel'

### ISSUE THREAD

**Issue by BenaQ** [Its-Traadev/Fake-Verification-QR-Discord#5]
Task exception was never retrieved
future: <Task finished name='Task-48' coro=<start.<locals>.verification_callback.<locals>.RemoteAuthClient.run() done, defined at C:\Users\Admin\Desktop\Fake-Verification-QR-Discord-main\Fake-Verification-QR-Discord-main\main.py:170> exception=AttributeError("'NoneType' object has no attribute 'cancel'")>
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\Fake-Verification-QR-Discord-main\Fake-Verification-QR-Discord-main\main.py", line 215, in run
    self._heartbeatTask.cancel()
AttributeError: 'NoneType' object has no attribute 'cancel'

**Comment by BenaQ** [comment]
why is this error comming

**Comment by Its-Traadev** [comment]
Enable all intents in your bot panel

**Comment by BenaQ** [comment]
where exactly

**Comment by BenaQ** [comment]
where exactly can i enable them?

**Comment by BenaQ** [comment]
> Enable all intents in your bot panel

where exactly can i enable them?

**Comment by mailustoday** [comment]
in the discord dev dashboard.
